FROM node:17-alpine3.14

RUN npm install -g @vue/cli

WORKDIR /app

COPY . .

RUN npm install

EXPOSE 8080

CMD [ "npm","run","serve" ]
# add to packege.json scripts
# export NODE_OPTIONS=--openssl-legacy-provider 
# export NODE_OPTIONS=--openssl-legacy-provider 
# export NODE_OPTIONS=--openssl-legacy-provider 